### ISSUE TITLE
Outlook webmail autolinking

### ISSUE THREAD

**Issue by M-J-Robbins** [JayOram/email-css-resets#11]
Outlook webmail is adding 
`<span data-markjs="true" class="HQEo7" tabindex="0" role="link">`

This isn't rendered as a link as such so we cant target it with an `a{}` but they do add a class, so we can remove all the styles by using 
```css
[class="HQEo7"]{
  border:none !important;
  cursor: auto !important;
  padding:0 !important;
}
```
Note that this is using an attribute selector as Outlook will prefix all class selectors with `x_`

**Comment by husseinalhammad** [comment]
`.HQEo7` seems to be an automatically generated class name. If so, this is likely to change on future updates. 

I think relying on `[role=link]` is a more futureproof approach. This is probably not unique enough though. So if we want to ensure these styles don't unintentionally apply to other email clients, we can rely on Outlook's `x_` class prefix:

```html
<body class="body">
  <!-- your email -->
</body>
```

```css
[class=x_body] [role=link] {
  border: none !important;
  padding: 0 !important;
  color: inherit !important;
}
```

The `cursor` property doesn't seem to be supported on Outlook web, but `color: inherit` is.
