### ISSUE TITLE
Outlook Android app

### ISSUE THREAD

**Issue by M-J-Robbins** [JayOram/email-css-resets#12]
The android version of Outlook adds `class="ms-outlook-linkify"` to generated links.

So adding this can help
```css
.ms-outlook-linkify{
  color: inherit !important;
}	
```
